/* Generated by Yosys 0.8 (git sha1 UNKNOWN, clang 7.0.1 -march=x86-64 -mtune=generic -O2 -fstack-protector-strong -fno-plt -fPIC -Os) */

(* top =  1  *)
(* src = "mux.v:1" *)
module mux(selector, reset, data_0, data_1, data_out);
  (* src = "mux.v:9" *)
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  (* src = "mux.v:4" *)
  input data_0;
  (* src = "mux.v:5" *)
  input data_1;
  (* src = "mux.v:6" *)
  output data_out;
  (* src = "mux.v:3" *)
  input reset;
  (* src = "mux.v:2" *)
  input selector;
  NOT _05_ (
    .A(selector),
    .Y(_03_)
  );
  NOT _06_ (
    .A(reset),
    .Y(_02_)
  );
  NAND _07_ (
    .A(data_1),
    .B(selector),
    .Y(_04_)
  );
  NAND _08_ (
    .A(data_0),
    .B(_03_),
    .Y(_01_)
  );
  NAND _09_ (
    .A(_04_),
    .B(_01_),
    .Y(_00_)
  );
  (* src = "mux.v:9" *)
  \$_DLATCH_P_  _10_ (
    .D(_00_),
    .E(_02_),
    .Q(data_out)
  );
endmodule
