/* Generated by Yosys 0.7+655 (git sha1 d36d1193, gcc 8.1.1 -march=x86-64 -mtune=generic -O2 -fstack-protector-strong -fno-plt -fPIC -Os) */

(* top =  1  *)
(* src = "mux.v:2" *)
module mux_estructural_ideal(clk, reset_L, data_0, data_1, data_out);
  (* src = "mux.v:12" *)
  wire [3:0] _00_;
  (* src = "mux.v:12" *)
  wire _01_;
  (* src = "mux.v:22" *)
  wire _02_;
  wire [3:0] _03_;
  (* src = "mux.v:3" *)
  input clk;
  (* src = "mux.v:5" *)
  input [3:0] data_0;
  (* src = "mux.v:6" *)
  input [3:0] data_1;
  (* src = "mux.v:7" *)
  output [3:0] data_out;
  reg [3:0] data_out;
  (* src = "mux.v:4" *)
  input reset_L;
  (* src = "mux.v:10" *)
  reg selector;
  assign _01_ = reset_L ? (* src = "mux.v:21" *) _02_ : 1'h0;
  assign _03_[0] = selector ? (* src = "mux.v:23" *) data_0[0] : data_1[0];
  assign _03_[1] = selector ? (* src = "mux.v:23" *) data_0[1] : data_1[1];
  assign _03_[2] = selector ? (* src = "mux.v:23" *) data_0[2] : data_1[2];
  assign _03_[3] = selector ? (* src = "mux.v:23" *) data_0[3] : data_1[3];
  assign _00_[0] = reset_L ? (* src = "mux.v:21" *) _03_[0] : 1'h0;
  assign _00_[1] = reset_L ? (* src = "mux.v:21" *) _03_[1] : 1'h0;
  assign _00_[2] = reset_L ? (* src = "mux.v:21" *) _03_[2] : 1'h0;
  assign _00_[3] = reset_L ? (* src = "mux.v:21" *) _03_[3] : 1'h0;
  assign _02_ = ~(* src = "mux.v:22" *) selector;
  (* src = "mux.v:12" *)
  always @(posedge clk)
      data_out[0] <= _00_[0];
  (* src = "mux.v:12" *)
  always @(posedge clk)
      data_out[1] <= _00_[1];
  (* src = "mux.v:12" *)
  always @(posedge clk)
      data_out[2] <= _00_[2];
  (* src = "mux.v:12" *)
  always @(posedge clk)
      data_out[3] <= _00_[3];
  (* src = "mux.v:12" *)
  always @(posedge clk)
      selector <= _01_;
endmodule
